sudo: false
language: scala

scala_212: &scala_212 2.12.14
scala_213: &scala_213 2.13.2

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

jdk:
  - openjdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

stages:
  - name: test
  - name: doc-deploy
    if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"

jobs:
  include:
    - &all_tests
      stage: test
      env: TEST="all_tests"
      scala: *scala_212
    - <<: *all_tests
      env: TEST="all_tests"
      scala: *scala_213
    - env: TEST="docs"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION docs/mdoc
        - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
        - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
      scala: *scala_212
    - stage: doc-deploy
      scala: *scala_212
      script:
        - sbt ++$TRAVIS_SCALA_VERSION docs/publishMicrosite
